schema: "classroom50/repo-config/v1"
classroom: "swdevprac2-69-1"
assignment: "a07-swdevprac2-69-1"
secret: "cf2djm54"
owner:
  username: "xerlaxtole"
  id: 115062385
  accepted_at: "2026-10-05T15:56:29Z"
source:
  owner: "SWDevPrac2-69-1"
  owner_id: 312147402
  repo: "2110507_a07_starter"
  branch: "main"
